version: "3"

x-restart-policy:
  &restart-policy
  restart: unless-stopped

services:
  bot:
    <<: *restart-policy
    pull_policy: build
    build: .
    depends_on: [ piston ]
    volumes:
      - ./logs:/bot/logs
  piston:
    <<: *restart-policy
    image: ghcr.io/engineer-man/piston
    environment:
      PISTON_REPO_URL: https://github.com/ooliver1/dewel/releases/download/pkgs/index.csv
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec
